[package]
edition = "2021"
name = "todo"
version = "0.1.0"
[dependencies]
colored = "*"
terminal_size = "*"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
chrono = "0.4.6"
