[package]
name = "todo"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.41"
inquire = {version = "0.7.5", features = ["chrono", "date", "editor"]}
itertools = "0.14.0"
